name: Docker Image PHP7.1 - FPM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'php71/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'php71/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout
      -
        name: ls -la
        run: ls -la
      -
        uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v2 
        name: Setup buildx
      -
        name: Build the php71
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.1-fpm:latest --push ./php71/.

